### ISSUE TITLE
Part 1: Breadth and Depth

### ISSUE THREAD

**Issue by btomey** [Vidmaster/cybr8420-group4#28]
Each top-level claim is argued using a broad and deep argument supported by appropriate evidence. The assurance case diagram is neatly organized; uses proper notation, and all elements are worded properly. The assurance case is convincing to a technical expert.

**Comment by Vidmaster** [comment]
I think we have adequate breadth and depth on our assurance cases at the moment! If there are no objections I'll close this out tomorrow.

**Comment by Vidmaster** [comment]
No feedback received here or in Slack, closing!
